//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovingCastles.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Gui {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Gui() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovingCastles.Text.Gui", typeof(Gui).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys:
        ///(e), (Enter)
        ///
        ///Brings up an overlay highlighting any adjacent objects that can be interacted with. Use the numpad to choose a direction, or (5) to choose the player&apos;s tile. If there is only one possible selection, pressing (e) or (Enter) again selects it..
        /// </summary>
        internal static string Command_Interact {
            get {
                return ResourceManager.GetString("Command_Interact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move with the numpad:
        ///
        ///\ | /
        ///- o -
        //// | \
        ///
        ///Tip:
        ///The center of the numpad (5) is used for waiting..
        /// </summary>
        internal static string Command_Movement {
            get {
                return ResourceManager.GetString("Command_Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move with the numpad.
        ///Rest with the middle of the numpad (5).
        ///Interact with (e) or (Enter).
        ///
        ///Mouse: (TODO)
        ///Left-click to move and attack.
        ///Right-click to inspect..
        /// </summary>
        internal static string Command_Overview {
            get {
                return ResourceManager.GetString("Command_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys:
        ///(z), (5), (.)
        ///
        ///Skip a turn.
        ///
        ///Tip:
        ///Wait to regain health or wait for the right time to strike, but remember that there is a limited amount of time in each day!.
        /// </summary>
        internal static string Command_Wait {
            get {
                return ResourceManager.GetString("Command_Wait", resourceCulture);
            }
        }
    }
}
