//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovingCastles.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Story {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Story() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovingCastles.Text.Story", typeof(Story).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The heavy boards of this rough trapdoor hum with power to your mage senses. Placing a hand on the wood, you can sense spells of preservation, strength and locking. You&apos;ll need a key or passphrase of some kind to get through here..
        /// </summary>
        internal static string AlwardsTower_TrapdoorStep {
            get {
                return ResourceManager.GetString("AlwardsTower_TrapdoorStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The musty air and dust-caked interior confirm what could be seen from outside. Although this is certainly Old Alward&apos;s Tower, there is no human living here, and hasn&apos;t been for some time..
        /// </summary>
        internal static string Entry_AlwardsTower_Entrance {
            get {
                return ResourceManager.GetString("Entry_AlwardsTower_Entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Alward&apos;s Tower, known as the Watcher over the Desert, is the traditional destination of pilgrims from the east. Like the fathers of centuries ago, you must cross the desert and find it before your journey to become a mage can truly begin..
        /// </summary>
        internal static string Entry_AlwardsTower_Quest {
            get {
                return ResourceManager.GetString("Entry_AlwardsTower_Quest", resourceCulture);
            }
        }
    }
}
